### ISSUE TITLE
Demo using GoogleColabratory

### ISSUE THREAD

**Issue by wakamezake** [tryolabs/norfair#10]
I made a demo that works with Googlecolabratory using [norfiar - yolov4 demo](https://github.com/tryolabs/norfair/tree/master/demos/yolov4) as a reference.
[GoogleColabratory - Yolov4 CarDetection Demo](https://colab.research.google.com/drive/1PK7VUmyHFeUbcM-4ovdkzlCxDIPOhC6z?usp=sharing)

I just couldn't find a video to use for the demo, so the results of the demo are hard to understand.
Can you tell me if you have any other good demo videos?

**Comment by joaqo** [comment]
Hi, thanks for taking the time to try out norfair! Just looked at your demo, and it seems YOLOv4 is having trouble detecting the cars. If you go frame by frame on your results, the red circles are the centroids of the detections we get from YOLOv4, and the filled circles with a numbers attached to them are the tracked objects returned by norfair. You can see that there are barely any detections for norfair to track, so there are not many tracked objects.

[Here](https://www.youtube.com/watch?v=aio9g9_xVio) you can see an example of one of the videos we used for the demo. YOLOv4 works much better here.

**Comment by wakamezake** [comment]
Updated demo using [video link](https://www.youtube.com/watch?v=aio9g9_xVio).
- [GoogleColabratory - Yolov4 CarDetection Demo](https://colab.research.google.com/drive/1PK7VUmyHFeUbcM-4ovdkzlCxDIPOhC6z?usp=sharing)

I have one last question, how do I change the font size or the size of the dots?

**Comment by joaqo** [comment]
That looks great! To change font/dot size you have to set in the arguments `radius`, `id_size`, and `id_thickness` in [`draw_tracked_objects`](https://github.com/tryolabs/norfair/blob/master/demos/detectron2/detectron2_cars.py#L35) as explained in the [draw_tracked_objects doc](https://github.com/tryolabs/norfair/tree/master/docs#draw_tracked_objects).
