### ISSUE TITLE
Cannot import name 'Paths' from Norfair Error

### ISSUE THREAD

**Issue by BaranGursoy** [tryolabs/norfair#102]
I'm coming across with this error on the title, and couldn't fix that. Norfair is installed with pip on Colab, but can't import Paths from it. Thanks in advance!

**Comment by joaqo** [comment]
I think this is probably due to you using Norfair on python 3.6, is this correct? That version of python installs an old version of Norfair, which doesn't work with our demos. We're working to fix this though!

**Comment by usamaamjad7** [comment]
Iam using google colab for running yolov5 demo code .it will also show this same error what i do know?
ImportError: cannot import name 'Paths' from 'norfair' (/usr/local/lib/python3.7/dist-packages/norfair/__init__.py)

**Comment by BarRozenman** [comment]
I have the same issue, I cannot import Paths, 

ubuntu==20.04.4
python==3.8.12
norfair==0.4.0 


error log:
`ImportError:
cannot import name 'Paths' from 'norfair' (/.../python3.8/site-packages/norfair/__init__.py)`

any help will be appreciated?

**Comment by joaqo** [comment]
Hi, thanks for the feedback! We just fixed this issue. The reason for it was that our releases were behind our demos, so not all features used in our demos were released in pypi. The latest Norfair release (v0.4.3) fixed this.

**Comment by usamaamjad7** [comment]
> Hi, thanks for the feedback! We just fixed this issue. The reason for it was that our releases were behind our demos, so not all features used in our demos were released in pypi. The latest Norfair release (v0.4.3) fixed this.

thanks @joaqo for solving this issue.
