### ISSUE TITLE
Pose tracking

### ISSUE THREAD

**Issue by alejoGT1202** [tryolabs/norfair#103]
Hello,

I've a file that contains keypoints from my objects from all the frames of my video. I convert this values into numpy arrays to pass them to the norfair Detection object, which works correct. However, the don't always have the same shape in all the frames sometimes they have shape (11,2) frame n and in frame n+1 the shape is (10,2) which led me to the following error.

```
distances = np.linalg.norm(detected_pose.points - tracked_pose.estimate, axis=1)
ValueError: operands could not be broadcast together with shapes (11,2) (10,2) 
```
I'm trying to use this [script ](https://github.com/tryolabs/norfair/blob/master/demos/openpose/openpose_extrapolation.py ) as reference to develop my own one. 

Thank you for the help.

**Comment by joaqo** [comment]
Hi! Regretably Norfair doesn't support dynamically changing detection array shapes.

One thing you could try though, is it to keep the shape of the detection static, but set 0 score to the keypoints that don't appear in that frame, Norfair will ignore them.
