### ISSUE TITLE
Keypoint RCNN integration

### ISSUE THREAD

**Issue by alejoGT1202** [tryolabs/norfair#107]
Hi,

I'm trying to integrate the pose tracking algorithm example into keypoint RCNN detection model but I'm getting the an error when I pass the Detected objects into the tracker.

I'm converting the detected keypoints and it's scores into a `norfair.Detection` object using the following code: 

`detections = [norfair.Detection(points=keypoints_array,scores=scores_array)]`

After doing that conversion I check that I've values stored in my `detections` and I got the following output:

```[array([[1608.734  ,  633.5016 ],
       [1594.391  ,  650.7872 ],
       [1580.048  ,  440.47913],
       [1528.4133 ,  440.47913],
       [1528.4133 ,  440.47913],
       [1544.1904 ,  508.18106],
       [1491.1215 ,  515.38336],
       [1557.0992 ,  588.84717],
       [1482.5157 ,  640.7039 ],
       [1594.391  ,  624.8588 ],
       [1584.3508 ,  675.2751 ],
       [1506.8988 ,  727.1319 ],
       [1491.1215 ,  732.89374],
       [1663.2372 ,  725.69147],
       [1673.2773 ,  730.0129 ],
       [1571.4421 ,  715.6082 ],
       [1570.0079 ,  717.0486 ]], dtype=float32)] [array([-1.0204245 , -0.23408791, -2.384819  , -1.9272052 ,  0.8853889 ,
        3.2817383 ,  7.810372  ,  2.475178  , 11.387346  ,  4.371869  ,
       10.931066  ,  3.5870967 ,  3.786034  , -0.7125755 , -0.56321704,
       -2.1999962 , -0.9299965 ], dtype=float32)] 
 ```

Where the first array contains the keypoints I want to track and the second array their scores However when I pass the detections to the tracker I get the following error:

```
ERROR: The detection list fed into `tracker.update()` should be composed of <class 'norfair.tracker.Detection'> objects not <class 'norfair.tracker.Detection'>.
```

Should I change the data type of my arrays?

**Comment by joaqo** [comment]
Hi! Thanks for the feedback. The error message you received is actually incorrect, and is not really reflecting what is happening in your case. We'll have to fix our error message on our end, so thanks for the feedback!

Regarding your error, I think the array you sent to `Detection` is incorrectly shaped, but I can't really tell by looking at that text you copied, as it is not complete.

You can check the docs [here](https://github.com/tryolabs/norfair/blob/master/docs/README.md#detection) which detail what format of array `Detection` expects.
