### ISSUE TITLE
[Feature Request] StrongSORT

### ISSUE THREAD

**Issue by austinmw** [tryolabs/norfair#111]
Hi, I wonder if it would be possible for this repo to support [StrongSORT](https://github.com/dyhBUPT/StrongSORT)? Since this is ranked #1 in IDF1 on paperswithcode for MOT20 and other datasets.

**Comment by joaqo** [comment]
Hey, thanks for the suggestion! We wont be integrating StrongSORT currently, but we'll be soon adding support for fully integrated re-id using embeddings inside Norfair, which I believe has some overlap with StrongSORT.

**Comment by dekked** [comment]
I am closing this issues since this is merged https://github.com/tryolabs/norfair/pull/118

With this feature, you can use the embeddings you most like!
