### ISSUE TITLE
3D point tracking?

### ISSUE THREAD

**Issue by kennethhoffmann** [tryolabs/norfair#112]
Hi!

I wanted to see if this could  be used to track 3d points(x,y,z) in space, rather than just 2d (x,y) points?

Thanks

Kenneth

**Comment by kennethhoffmann** [comment]
Ended up modifying the code to work with 3D objects. 

Has anyone changed the Kalman Filter to an IMM filter? I plan on doing this but I wonder if it's better to do some before the tracker or after the tracker.

**Comment by joaqo** [comment]
Hey, this sounds cool! If you wish to write a PR to add this for Norfair, we may be interested if the added complexity is low.

**Comment by dekked** [comment]
For anyone that has the same problem, we added this reference PR https://github.com/tryolabs/norfair/pull/117
