### ISSUE TITLE
Dose it Handle the Occlusions (yolov5)?

### ISSUE THREAD

**Issue by bwithai** [tryolabs/norfair#124]
Hi hope you will be doing well

my tracking camera move accordingly as object moves to track the obj lets it (person) suddenly occlusion appear.

I want to track the velocity of the object in occlusion and move on prediction that it might be moving (focus on not miss the enemy). camera is placed on gun.

Explanation of 1, 2, 3

1. camera track the person at (1) and moving accordingly as object move but,
2. at point (2) occlusion appear detection loss and object keep moving,
3. at point (3) we loss the object

Please give your precious time sincerely
![image](https://user-images.githubusercontent.com/76056239/174425686-10e0803e-e4cf-4689-a593-bc1968b2d848.png)

**Comment by dekked** [comment]
It will handle the occlusion based on an extrapolation of where Norfair thinks the object will be (Kalman filter).

For this, you will have to do some tuning depending on your use case (`hit_counter_max`, `initialization_delay`, ...).

**Comment by bwithai** [comment]
@dekked thanks for your response.

yolov5+DeepSORT mention this https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/368.

I also mention my point there -> https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/408 

but the ReID concept can't handle my scenario.

**Can you give me some clue or reference some other Tracker Please give some time Thanks**
