### ISSUE TITLE
Norfair Vs. ByteTracker or DeepSort Inference Speed

### ISSUE THREAD

**Issue by Rm1n90** [tryolabs/norfair#126]
Hello @joaqo,

I have a question regard to speed of Norfair tracking...
Im using YoloV5 as a object detector for both NorFair and ByteTracker (or DeepSort) tracking algorithms with the same setting. However, all the process for one frame (Detection and tracking) took almost ~14ms for ByteTracker and ~45ms for Norfair. I would like to ask you how can I increase the inference time of Norfair?

Thanks!

**Comment by mgultekin** [comment]
Hi @Rm1n90,
I am also using Bytetracker recently, what you think about the tracking performance comparison between these two trackers?

**Comment by Interpause** [comment]
I think one difference between NorFair and other trackers is that NorFair is designed more as a framework for tracking, allowing the user to bring their own method for associating keypoints. Meaning other trackers can be implemented using NorFair in a sense.

**Comment by MyraBaba** [comment]
@mgultekin  Hi ,

would you mind to share the python repo for bytetracker ?  if yolov7 integration would be best

**Comment by m-alcu** [comment]
This comparison dives that faster algotitm is ByteTracker

https://mpolinowski.github.io/docs/IoT-and-Machine-Learning/ML/2023-02-15-as-one-yolo-object-tracking/2023-02-15/
