### ISSUE TITLE
[Feature Request] ROS Integration

### ISSUE THREAD

**Issue by Interpause** [tryolabs/norfair#127]
The Robot Operating System is a framework for advanced robotics. I think there is a use case for creating a ROS Node for object tracking via NorFair.

**Comment by dekked** [comment]
We just published [a blog post on ROS](https://tryolabs.com/blog/2022/09/15/ros-the-framework-to-accelerate-your-next-robotics-project), so this makes sense.

We will consider this feature request in the future.

**Comment by Interpause** [comment]
I actually ended up making a tracking node based on NorFair and the corresponding message types needed, but mostly for my own project so the code isn't in any state to be re-used anywhere else.

**Comment by dekked** [comment]
Did you make a node that only does tracking, and therefore depends on a separate node with the detector? Or is your node integrating detector+Norfair tracking?

**Comment by Interpause** [comment]
> Did you make a node that only does tracking, and therefore depends on a separate node with the detector? Or is your node integrating detector+Norfair tracking?

Separate detector. Actually here is the code for my tracker: https://github.com/ConfusionTechnologies/ros-mot-node.

The main reason I don't think its easily reuseable is cause it depends on micro-framework I made on top ROS2 to simplify stuff such as parameter declaration. Also, all my message definitions are centralized in that micro-framework. 

That, and the detector node, is available on the organization account I made to separate the repositories from my personal account.

**Comment by dekked** [comment]
Thanks for this @Interpause!

Can probably leverage this when we build a reusable ROS node for Norfair.

What license are you releasing your code under?

**Comment by Interpause** [comment]
MIT. Didn't include the license because I didn't expect other people to use them, but I am fine with giving my code.

**Comment by Interpause** [comment]
Nice, thanks!
