### ISSUE TITLE
getting none for labels = True

### ISSUE THREAD

**Issue by DemonIncarnate** [tryolabs/norfair#132]
Hi i am trying to run yolo with norfair on a video stream,even the object is getting detected and i am getting bbox around them the draw_labels gives none label for all object.Am i missing something? i was getting proper labels for same objects when using simple yolo

**Comment by facundo-lezama** [comment]
Hi @DemonIncarnate! 

Can you give some more information on how you're using the labels? In the [docs](https://github.com/tryolabs/norfair/tree/master/docs#detection), you can see how labels should be handled in `Detection` objects. Also, [this](https://github.com/tryolabs/norfair/blob/master/demos/keypoints_bounding_boxes/keypoints_bounding_boxes_demo.py) demo shows the usage both for tracking with labels and drawing them.
