### ISSUE TITLE
Scores from tracked points

### ISSUE THREAD

**Issue by alejoGT1202** [tryolabs/norfair#133]
Hello,

Is it possible to get the scores from the tracked keypoints?

**Comment by aguscas** [comment]
Do you mean the scores returned by your detector? In that case, for each tracked object you can see the `last_detection` attribute, which should have the `scores` attribute if you provided it when you generated your list of norfair `Detections` that was used as an argument for the `tracker.update` method. I am not sure if this is what you are asking

**Comment by alejoGT1202** [comment]
Yes that is what I was asking, thanks for the help.
