### ISSUE TITLE
This thread mentions a demo showing improved accuracy, but I can't seem to find it in the branch - was it included?

### ISSUE THREAD

**Issue by polyted** [tryolabs/norfair#136]
This thread mentions a demo showing improved accuracy, but I can't seem to find it in the branch - was it included?

_Originally posted by @polyted in https://github.com/tryolabs/norfair/issues/118#issuecomment-1202618702_

**Comment by dekked** [comment]
Hi @polyted!

The ReID feature is not yet ready, but we are starting to work on this demo so we can release it soon.

**Comment by JuanFKurucz** [comment]
Hey @polyted , we now added a simple ReID demo using a simulation in #118

**Comment by dekked** [comment]
#118 has been merged so I am closing this issue!

@polyted I hope you find the demo helpful :)
