### ISSUE TITLE
Feature Request: Will you add the Yolov7 model?

### ISSUE THREAD

**Issue by kadirnar** [tryolabs/norfair#140]
What should I do to add a new YOLO model?

**Comment by facundo-lezama** [comment]
Hi @kadirnar! 

Other than adapting Yolov7 detections to be compatible with Norfair's `Detection` class, there shouldn't be any issues with using it. 

If you're asking for a demo of Norfair using Yolov7, that can be an exciting addition. We can add it to our backlog.

**Comment by kadirnar** [comment]
@facundo-lezama  I tested the Norfair library yolov7 model. I sent PR.
