### ISSUE TITLE
UnboundLocalError: local variable 'points' referenced before assignment

### ISSUE THREAD

**Issue by Tommyhillphyga** [tryolabs/norfair#148]
The function "Draw_tracked_boxs" throws an "UnboundLocalError" when the "draw_box" parameter is set to False.  
Error message --- UnboundLocalError: local variable 'points' referenced before assignment.

**Comment by Tommyhillphyga** [comment]
points = obj.estimate
 points = points.astype(int)

These two expressions above are missing from the if statement.
![Screenshot (263)](https://user-images.githubusercontent.com/64691496/185797972-e4bd8795-fc29-4e8e-8441-00c9ab78542a.png)

**Comment by javiber** [comment]
Thanks for reporting this @Tommyhillphyga! we will merge this fix soon
