### ISSUE TITLE
How can I make the id assignments faster?

### ISSUE THREAD

**Issue by DeepKeys** [tryolabs/norfair#153]
I have implemented the tracker and everything is working, but it is too slow for my application. Objects are passing by very quickly.

What I mean is, that if an object comes into frame, my object detector immediately spots the object. So my 'detections' variable is nonempty. Only if the object is in view for a long time (like 15 frames or 1.5 seconds I'm estimating), then 'tracked_objects' becomes non-empty as well. Which of the following variables (see below) of the tracker can I change to make the tracker immediately assign id's to the object instead of only after a certain amount of frames?

```
detections = yolo_detections_to_norfair_detections(results, track_points="centroid")
tracked_objects = tracker.update(detections=detections)
```

These are the variables I should be able to change to make the algorithm quicker. (I don't really see what the purpose of the hitcounter is, so that is the reason why I'm posting this question here):
```
distance_function=frobenius,
distance_threshold=3.33,
hit_counter_max=15,
initialization_delay=None,
pointwise_hit_counter_max=4,
past_detections_length=4
```

Thanks for the help

**Comment by javiber** [comment]
Hi @DeepKeys
There are a few possible reasons why the tracked objects take too long to be initialized, a couple of thing to try (in order) are:

1. Set the `initialization_delay` of the tracker to a lower number. If I understood correctly you're not passing it so it defaults to `int(self.hit_counter_max / 2) -> 7` we found `3` to be a good starting point. Keep in mind that reducing this number can increase false positives.
2. Another thing to try is increasing the `distance_threshold`, I don't have a good suggestion here but just try higher numbers. This number limits how far a detection and a tracked object can be matched, if the threshold is lower than what your objects move from frame to frame the tracker could have a hard time making the matches.

Answering your other question, `hit_counter` on a `TrackedObject` is a simple integer that represents how much evidence we have that this is an object (you can also think of it as a type of inertia if you are familiar with it), it start in 1 by default then every time we successfully matched a `Detection` to this `TrackedObject` we increase it by 1. When the `hit_counter` is greater than `initialization_delay` we consider this object to be "alive" and we start returning it on the update.

The hit_counter keeps increasing until it reaches `hit_counter_max` where we just cap it.

Every time we don't find a matching `Detection` for a `TrackedObject` we decrease the `hit_counter` by 1, when it reaches 0 we consider the `TrackedObject` as "dead" and stop returning it.

Hope that clarifies what `hit_counter_max` and `initialization_delay` mean. We are working on a new documentation, a preview is available [here](https://tryolabs.github.io/norfair/reference/tracker/#norfair.tracker.Tracker) is not yet finished but it might be helpful.

Will close the issue with this comment but feel free to re-open if you have further questions.

Cheers

**Comment by DeepKeys** [comment]
Thank you! This worked like a charm
