### ISSUE TITLE
Tracker used in norfair?

### ISSUE THREAD

**Issue by IamUmairImran** [tryolabs/norfair#159]
Hi, 
Which tracker is being used in this library?

**Comment by dekked** [comment]
We are using our own implementation that is derived from SORT, but generalized ([see here](https://github.com/tryolabs/norfair#how-it-works)). The most basic form is therefore using a Kalman filter for extrapolating the positions of objects.

However, as the distance function is customizable by the user, and we support appearance embeddings, it is actually possible to implement other existing tracking methods using Norfair! You can check our demos for examples using different distance functions.

**Comment by dekked** [comment]
I am closing this issue, feel free to follow up if you have more questions!
