### ISSUE TITLE
Vertical MOV video output is flipped verticaly

### ISSUE THREAD

**Issue by diegomarvid** [tryolabs/norfair#186]
I recorded a video using an iPhone in MOV format and the output was flipped vertically.

The minimum code to reproduce the error is the following:

```python
from norfair import Video

video = Video(input_path='demo.mov')

for frame in video:
    video.write(frame)
```

The information in the video is the following:

<img width="268" alt="image" src="https://user-images.githubusercontent.com/33181424/191769580-4559e4a9-5172-44d5-82fc-a1f1041d4525.png">

**Comment by dekked** [comment]
Does it happen consistently with every MOV video whether it's filmed vertically or horizontally?

**Comment by diegomarvid** [comment]
Only when it's filmed vertically
