### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by joshfox10** [tryolabs/norfair#190]
It appears the documentation is no longer available since the link does not appear to work.  Is there somewhere else I can obtain the documentation?

**Comment by dekked** [comment]
Hi @joshfox10!

The documentation is available on this site: https://tryolabs.github.io/norfair/

The links in the main README seem to work.

Can you specify which link is broken for you?

Thanks!

**Comment by dekked** [comment]
I am unsure what you mean. [Here is the documentation on Paths](https://tryolabs.github.io/norfair/reference/drawing/#norfair.drawing.Paths).

![image](https://user-images.githubusercontent.com/1590959/192317995-c51565f6-6d60-4ed0-8081-7231972550f9.png)

Using the menu on the left you can read the docs for each one of the classes. Is this what you were looking for?
