### ISSUE TITLE
making it threaded?

### ISSUE THREAD

**Issue by kodonnell** [tryolabs/norfair#21]
In our experience, tracking runtime can be greatly reduced by threading each of the individual tracked objects (in this case `TrackedObject`) as there's less blocking etc. I don't have exact numbers, but it could easily be 10x with lots of objects and not-to-expensive detector. It's pretty easy to do as well.

Would there be interest in this? My proposal would be to have a single-threaded or multi-threaded mode, as the former can be easier to debug etc.

**Comment by joaqo** [comment]
Hi, thanks for taking the time to propose improvements.

During development we decided not to spend too much time on making the algorithm run fast, as we were using large neural networks as detectors underneath Norfair, which made the time the tracker added comparatively negligible. But lately we've been working with small networks, and things that run on the edge, and we are starting to find that norfair can add a non-negligible amount of inference time.

For this reason we plan to start working on optimizing Norfair's performance.. There's a bunch of low hanging fruits we'll tackle before thinking about parallelization, but it is something we may try in the future.

Thanks again, and please any other ideas you may have are definitely welcome.
