### ISSUE TITLE
Draw scores in Detection boxes

### ISSUE THREAD

**Issue by moooises** [tryolabs/norfair#216]
Hello,

I have been checking out this library the last few days and it looks pretty good.
However, I had trouble drawing each detector's score in its boxes. The **[draw_boxes](https://tryolabs.github.io/norfair/2.1.1/reference/drawing/#norfair.drawing.draw_boxes)** function allows you to draw the labels but not the scores.
I made a modifided version of that function that allow me to draw the scores, but I was wondering if there is an official way to do it or if It will be added in the future.

Thank you.

**Comment by javiber** [comment]
Hi @moooises There is no parameter to include the score when drawing but it should be a pretty easy thing to add, thanks for the suggestion!

Will flag this issue as a good first issue for someone trying to contribute to norfair

**Comment by javiber** [comment]
How do you feel about making the PR yourself @moooises? We are always open to contributors and since you already implemented some of it it would be easier. I can help you with the implementation/documentation or whatever you need

**Comment by moooises** [comment]
Yeah, I can try. 
Tomorrow Friday I have work to do, but I can do it on Saturday or Sunday.

**Comment by moooises** [comment]
Hi @javiber,
I'm having some problems preparing the setup for the Contributing.
After installing pyenv, poetry and preparing every python version, I get an error when running **poetry run tox**, but only with Python 3.7.X , with the other versions I don't have any errors.
It says that the module named "rich" is not installed. I tried to install it manually, but it doesn't seems to work.
I'm using pyenv for windows.

**Comment by moooises** [comment]
Hi @javiber,
I'm having some problems preparing the setup for the Contributing.
After installing pyenv, poetry and preparing every python version, I get an error when running poetry run tox, but only with Python 3.7.X , with the other versions I don't have any errors.
It says that the module named "rich" is not installed. I tried to install it manually, but it doesn't seems to work.
I'm using pyenv for windows.

**Comment by moooises** [comment]
Hi @javiber,
I'm having some problems preparing the setup for the Contributing.
After installing pyenv, poetry and preparing every python version, I get an error when running poetry run tox, but only with Python 3.7.X , with the other versions I don't have any errors.
It says that the module named "rich" is not installed. I tried to install it manually, but it doesn't seems to work.
I'm using pyenv for windows.

**Comment by javiber** [comment]
That's weird, I'll look into it on Monday. For now just ignore that error, you should be able to develop normally when it the tests are failing

**Comment by javiber** [comment]
Couldn't reproduce the error you mentioned but as pointed out in our contributing guide you are encouraged not to run the tests locally and instead create the PR and let Github run the tests. If they fail on GitHub you might decide to run them locally but there is no need to run them beforehand
