### ISSUE TITLE
"reid_hit_counter" Keeps Decreasing Causing Long-living Objects To Killed Suddenly

### ISSUE THREAD

**Issue by h-sh-h** [tryolabs/norfair#223]
Hi & Thanks for your wonderful library.

I run your tracker with "reid" feature enabled and it seems like there is a small bug in calculating "reid_hit_counter". (Although it seems too obvious so probably I am missing a point)

As the document stated :

> Each tracked object keeps an internal ReID hit counter which tracks how often it's getting recognized by another tracker, each time it gets a match this counter goes up, and each time it doesn't it goes down. If it goes below 0 the object gets destroyed. If used, this argument (`reid_hit_counter_max`) defines how long an object can live without getting matched to any detections, before it is destroyed.

But there is no code for increasing the value of 'reid_hit_counter'. The only part of the code which I found is in `tracker_step` :
```python
    def tracker_step(self):
        self.hit_counter -= 1
        if self.reid_hit_counter is None:
            if self.hit_counter <= 0:
                self.reid_hit_counter = self.reid_hit_counter_max
        else:
            self.reid_hit_counter -= 1
        self.point_hit_counter -= 1
        self.age += 1
        # Advances the tracker's state
        self.filter.predict()
```

So even if the object is "alive", `reid_hit_counter` keeps decreasing and as soon as it gets to zero, according to this section of the code :
```python
if self.reid_hit_counter_max is None:
            self.tracked_objects = [
                o for o in self.tracked_objects if o.hit_counter_is_positive
            ]
            alive_objects = self.tracked_objects
        else:
            tracked_objects = []
            for o in self.tracked_objects:
                if o.reid_hit_counter_is_positive:
                    tracked_objects.append(o)
                    if o.hit_counter_is_positive:
                        alive_objects.append(o)
                    else:
                        dead_objects.append(o)
```
that object gets suddenly destroyed.
It happens mostly to a long living objects in the scene which `reid_hit_counter` has time to get zero.
Looks like the "alive" objects should not get their `reid_hit_counter` decreased. 

Thanks in advance

**Comment by h-sh-h** [comment]
I can post you a video of this happening if it helps.

**Comment by h-sh-h** [comment]
Hi @aguscas 
I got the idea of what you are saying and it looks like norfair intended to implement the behaviour that you say but what I see in action is different.

I think there should be an additional condition of "tracked object is initialized" on setting `reid_hit_counter` to max when `hit_counter` becomes zero in `tracker_step` function.

**Comment by h-sh-h** [comment]
@facundo-lezama Thanks for the fix.
Nothing better than a cool library with bunch of fast response developers!
Will certainly test that.
Currently my next step after testing and validating my code is:
1.Implementing a norfair like tracker library in C++ optimized for embedded devices.
2. Extending norfair library to support trackers like "multi-hypothesis" ones. (Something like MATLAB MOT tracking toolbox)

**Comment by facundo-lezama** [comment]
@h-sh-h glad to hear that! Those seem like great steps; I haven't gotten into "multi-hypothesis" trackers, but I will definitely take a look. 

Please let us know if you find any exciting additions for Norfair, we are always open to new ideas!
