### ISSUE TITLE
Not able to make re-identification work.

### ISSUE THREAD

**Issue by moooises** [tryolabs/norfair#225]
Hello,

I'm having many problems with the re id feature and I can't make it work.

I have been able to implement a neural network model to compare images and include it in **reid_distance_function**, but when I run the program with a video it doesn't seems to work.

I used a **reid_distance_threshold** of 0.9, because the model scores around that value when the images are very similar and tried changing the **reid_hit_counter_max** to bigger or smaller values, but I can't make it work.

I leave here my distance function in case the problem is in the function itself. The **loadModel** function return the comparion score.
```
def embedding_distance(matched_not_init_trackers, unmatched_trackers):
    imageLast = unmatched_trackers.last_detection.embedding
    #print("Entado en embedding")
    if imageLast is None:
        for detection in reversed(unmatched_trackers.past_detections):
            if detection.embedding is not None:
                imageLast = detection.embedding
                break
        else:
            return 1

    for detection_fst in matched_not_init_trackers.past_detections:
        if detection_fst.embedding is None:
            continue
        else:
            ImageInit=detection_fst.embedding

        distance=loadModel(ImageInit, imageLast)
        #print("distance")
        #print(distance)
        if(distance > 0.9):
            return distance

    return 1
```
I leave here a result video, so you can see my problem. Around the minute 0:14 you can see it can't handle an oclusion made by the  streetlight. [Video](https://drive.google.com/file/d/1zpU5GECVCR95oOPDWAbk5jRvZ9xUBjEO/view?usp=sharing). 
The paremeters are the distance function from above,  **reid_distance_threshold** of 0.9 and **reid_hit_counter_max** of 500. The images that the model compares are the one in the tracked boxes. I used a little function to crop the images.

**Comment by moooises** [comment]
I have just found what was wrong.

In the reid example they make **distance = 1 - cv2.compareHist** and I didn't know that distance needed to be less than the **reid_distance_threshold**. Now I can made the re-identification work.

**Comment by moooises** [comment]
Hi @AbinashSankaran 
Every detection object in Norfair has a **embedding** attribute, you need to asign there the data needed to calculate the embedding distance that wll be used to re-id. In my case, it was a cropped image of the object detected by the detection.
Also, you need to create a function to calculte the embedding distance and assing it to **reid_distance_function** in the **Tracker** Object properties. Inside this function is where you call your own re-id model with the data you assinged to embedding attribute of each detection.

I will leave you my code here, in case it might help you. I used this re-id model to test it: [vehicle_reid](https://github.com/regob/vehicle_reid) ,with the zoo model from Yolov7 as Detection Model.
The Norfair Code: [https://drive.google.com/file/d/1ZXw64mrFCcQbuBDesLaq7Xw2epcAO7b3/view?usp=sharing](https://drive.google.com/file/d/1ZXw64mrFCcQbuBDesLaq7Xw2epcAO7b3/view?usp=sharing)
and a code I made to extract the features of each cropped image: [https://drive.google.com/file/d/1-pdai6fn4w2pQV0JurKXLJf_YvSu1jFa/view?usp=sharing](https://drive.google.com/file/d/1-pdai6fn4w2pQV0JurKXLJf_YvSu1jFa/view?usp=sharing
)

The results I had where a bit mixed with the vehicle_reid model. With a lot objects, the re-identification didn't work properly. It re-identified some objects, the more different ones, but with rest it didn't work properly. However, with one or a few very different objects, the model worked fine.

If you made and train your own model, maybe you will get better results.

**Comment by Daheer** [comment]
> Hi [@AbinashSankaran](https://github.com/AbinashSankaran) Every detection object in Norfair has a **embedding** attribute, you need to asign there the data needed to calculate the embedding distance that wll be used to re-id. In my case, it was a cropped image of the object detected by the detection. Also, you need to create a function to calculte the embedding distance and assing it to **reid_distance_function** in the **Tracker** Object properties. Inside this function is where you call your own re-id model with the data you assinged to embedding attribute of each detection.
> 
> I will leave you my code here, in case it might help you. I used this re-id model to test it: [vehicle_reid](https://github.com/regob/vehicle_reid) ,with the zoo model from Yolov7 as Detection Model. The Norfair Code: https://drive.google.com/file/d/1ZXw64mrFCcQbuBDesLaq7Xw2epcAO7b3/view?usp=sharing and a code I made to extract the features of each cropped image: https://drive.google.com/file/d/1-pdai6fn4w2pQV0JurKXLJf_YvSu1jFa/view?usp=sharing
> 
> The results I had where a bit mixed with the vehicle_reid model. With a lot objects, the re-identification didn't work properly. It re-identified some objects, the more different ones, but with the rest, it didn't work properly. However, with one or a few very different objects, the model worked fine.
> 
> If you made and train your own model, maybe you will get better results.

Hi, @moooises could you share the files again? It's no longer available and would greatly help me out! Thanks

**Comment by moooises** [comment]
Sorry, I'don't have them anymore.
That google drive account was from my last job and they probably deleted the account.
