### ISSUE TITLE
Track objects and save unique copy as a image

### ISSUE THREAD

**Issue by Swalii** [tryolabs/norfair#242]
**Describe the situation you are working on**

I want to express my gratitude for this incredible project. I am utilizing the YOLOv5 model for object detection and have trained a custom model to detect vehicles and license plates with different classes. My goal is to capture unique objects from a webcam video stream in order to obtain license plate numbers using OCR .  For example, if I track a vehicle in a frame and it exists for a certain amount of time, I do not want to save multiple copies of the object as an image. I am new to the field of machine learning and apologize if this is an obvious question or already exists in the solution.

**Describe what is it that you need help with**
I am looking for guidance on the steps to take and, if possible, a reference to follow for deploying my vehicle and license plate detection project using YOLOv5 model to a production environment.

**Comment by DiegoFernandezC** [comment]
Hi @Swalii ,

Norfair will assign a unique ID to each object detected by your detector, and it will try to maintain this association throughout the video. This way, you can save the IDs of the vehicles that have already been seen, and use this information to decide whether to save a new image of an object or not.
Probably [this demo](https://github.com/tryolabs/norfair/tree/master/demos/yolov5) that uses YOLOv5 could be useful for you if you do not have experience with Norfair.

However, you should be cautious about losing track of objects after occlusion or some ID switching, especially if your video is complex. These changes in the objects' IDs can result in errors. You can find more information on how to solve some of these common problems in the Norfair documentation, specifically in the section on [Tracking issues](https://tryolabs.github.io/norfair/2.2/getting_started/#tracking-issues).

Regarding the deployment process, it will depend on your specific application. It likely starts by building a Docker image that contains the project with all necessary information (models, code, API, and anything else you need), with locked dependencies. Once your project is working, you will need to decide where you want to deploy it, in the cloud, locally on a physical machine, etc.
The deployment process is not so simple as to give you a detailed solution and depends a lot on your particular case.
If you have problems with the Norfair deployment, do not hesitate to consult again adding more information.

**Comment by Swalii** [comment]
@DiegoFernandezC 

I really appreciate the time and effort you took to provide such detailed information, I was able to successfully solve the problem with awesome Norfair, I will update the repo and share,  can help others with similar problems.
