### ISSUE TITLE
need direction with optical flow

### ISSUE THREAD

**Issue by bwithai** [tryolabs/norfair#246]
**Describe the situation you are working on**
I want to implement optical flow which give the direction of the object

**Describe what is it that you need help with**
I tried the `from norfair.camera_motion import MotionEstimator` function which give me this

![Screenshot from 2023-01-25 23-14-44](https://user-images.githubusercontent.com/76056239/214648188-c6670fbd-cca5-404a-b6ca-8caa52b2a398.png)

But I need the direction like this

![image](https://user-images.githubusercontent.com/76056239/214646935-03ce8186-f642-46e1-b7d8-2127e81ef3ea.png)

**Additional context**
Please help me i will be thankful for your time

**Comment by DiegoFernandezC** [comment]
Hi @bwithai 

The motion estimation function is used to estimate the movement of the camera, not the movement of the detections.

I'd like to ask you a question to make sure we understand your use case. Would you like to get a vector indicating the direction for each detection? Is the camera still, moving, or both?

**Comment by bwithai** [comment]
Thank you so much for your prompt response dear @DiegoFernandezC ,

Yes I need direction of each detected object. my focus is on the moving object but it will be bonus if possible for both.

give me hint to draw a direction arrow rather then a line followed by point.

Once again thank you so much for your response.

**Comment by bwithai** [comment]
may be this https://github.com/tryolabs/norfair/blob/24ea0134ffa60fe1b1bcf7a12879cf30c8fd616e/norfair/camera_motion.py#L394

will help you to get arrow direction.

**Comment by bwithai** [comment]
Thank you so much for providing such beautiful tracker :heart: 

I have done with my need by updating `cv2.circle()` to `cv2.arrowedLine()`
