### ISSUE TITLE
Implementation of YOLOv5 in Colab demo

### ISSUE THREAD

**Issue by Khrystofor19** [tryolabs/norfair#247]
**Describe the situation you are working on**
_A clear and concise description of your use case._
Hi! My apologies for raising the issue, I'm very new to the field; could you, please, help me to implement the Colab demo with YOLOv5? It's currently running on YOLOv7 and has all the functionality I need for my current project but I'm having trouble implementing YOLOv5 in it. I tried to do it through modification of current yolov5 demo but apparently it's using older functions so I was unable to implement trajectory drawing.
**Describe what is it that you need help with**
_A clear and concise description of what you don't understand or need help with._
Use YOLOv5 model in current Colab demo. I have a pre-trained custom model that worked with [yolov5 demo](https://github.com/tryolabs/norfair/tree/master/demos/yolov5/src) but I'm having trouble implementing all the functionality from current Colab demo (namely trajectory drawing).
**Additional context**
_Add any other context about the problem here._

**Comment by DiegoFernandezC** [comment]
Hi @Khrystofor19 

We made [this](https://colab.research.google.com/drive/1txeAy9SCDEDzodB0IMteVPeHlRjig9WS?usp=sharing) Colab that implements the path-drawing feature with the `YOLOv5` model. Remember to run this demo with the GPU, the path-drawing feature needs more resources.
We hope that it will be useful.

Greetings.
