### ISSUE TITLE
Reducing the match rate for TrackedObject's initialization

### ISSUE THREAD

**Issue by legend-k** [tryolabs/norfair#25]
How do i reduce the match rate to initialize a TrackedObject faster?

**Comment by joaqo** [comment]
Hi @legend-k, the current (sub-optimal) way to do it is to reduce both `hit_inertia_min` and `hit_inertia_max`. This is not good design though, and we are adding a new argument to initialize objects faster. Stay tuned for the next release.

**Comment by joaqo** [comment]
Just merged the commit to enable this feature here: https://github.com/tryolabs/norfair/commit/435babce9bfeb7f9f47d859dbadff1e597c7520b

Its has not yet been released, so you'll have to clone the repo to be able to use it.

**Comment by legend-k** [comment]
Is this the number of hits after minimum hit inertia is reached?

**Comment by joaqo** [comment]
It is a choosable intermediary point between minimum and maximum hit inertia, at which we start considering the object to be 'real'. By default it is the midpoint between minimum and maximum hit inertia.

**Comment by legend-k** [comment]
Ok thanks!
