### ISSUE TITLE
Path drawer returns black frame with points on top

### ISSUE THREAD

**Issue by Arno989** [tryolabs/norfair#251]
**Describe the situation you are working on**
I'm trying to recreate the gif of the footballers in the README.md 

**Describe what is it that you need help with**
The frame returned by `path_drawer.draw(frame, tracked_objects)` is completely black except for the drawing itself.
I assume this isn't the desired functionality, instead I would expect the drawing to be on the image itself.
I'm aware this isn't an in-place function like the other drawers but since I give both the frame and the coordinates to this function it's not that far of a leap to expect I would get the drawing on the frame in return, instead of some dots on a black canvas.

**Additional context**
I would also like to mention that quite a bit of the documentation on 'https://tryolabs.github.io/norfair/2.2/reference' is out of date.
Multiple functions that are deprecated are still there and mainly add to the confusion since a lot of these functions are still referenced in the demo codes and code example snippets on the site itself.
A small example is `from norfair import Path` should be `from norfair import Paths`, but there are other examples to be found, maybe a little documentation cleanup is in order. I might have a look at that myself in the future just to help out.

All that being said I should mention that I absolutely LOVE your library, it saved me a whole bunch of headaches and even more time, it's the perfect module to adapt in an object recognition project for tracking solutions.
Sending lots of appreciation your way <3

**Comment by Arno989** [comment]
Nevermind, I just had to `cv2.add()` the two frames, sleep is often the best debugger.

**Comment by DiegoFernandezC** [comment]
Hey @Arno989.

Thank you for the words to Norfair and these findings on the documentation. We are always open to receiving contributions in that way.

Also, this draw's behavior is unexpected, we opened [this](https://github.com/tryolabs/norfair/pull/252) PR to fix this problem. We expect that the draw method returns the frame with the correct paths (like the `AbsolutePaths`' `draw` method) and you do not need to add extra lines to join the paths with the video frame.
