### ISSUE TITLE
Should prefer `raise` over `print()` + `exit()`

### ISSUE THREAD

**Issue by quantumdot** [tryolabs/norfair#256]
**Describe the bug**
In a few locations within this package, if some condition is not met, an error message is printed and then the interpreter is instructed to `exit()`. Instead it would be better to raise an exception and allow the consuming program to handle the error condition, perhaps via graceful exit itself. This especially poses an issue in scenarios involving multiprocessing as these error messages may become lost or cause a subprocess to exit but the main program continues to run. Another scenario where this causes issues is when using tqdm progress bars, which will tend to overwrite any standard output and causing the message to be lost. Finally, we lose any context for the error, since no stack trace is generated.

Here are some locations where errors are handled by printing then exiting:
- https://github.com/tryolabs/norfair/blob/705f87c142106497117b54dc3d37ca45d5caef20/norfair/tracker.py#L296-L300
- https://github.com/tryolabs/norfair/blob/705f87c142106497117b54dc3d37ca45d5caef20/norfair/tracker.py#L487-L491
- https://github.com/tryolabs/norfair/blob/50f560745219f0e5a6ccd312e7c7a173b3754b45/norfair/video.py#L178-L180
- https://github.com/tryolabs/norfair/blob/cda59f7f7914e62fa6c18f726414ff514ffb0ade/norfair/utils.py#L21-L30

**To Reproduce**
Any condition which would trigger one of the above conditionals.

**Expected behavior**
An exception would be raised, the consuming program can decide how to proceed.

**Screenshots or videos**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.8.12
 - Norfair version: 2.2.0

**Additional context**

**Comment by facundo-lezama** [comment]
Hi @quantumdot, thanks for your observation. This behavior was defined a long time ago, and it isn't a bug, actually. Until now, we didn't have the need to change this, so we left it like this. 

If you need this behavior to change, we encourage you to open a PR with the changes!

**Comment by facundo-lezama** [comment]
Sorry I didn't have the time to look at it. I'll make some time this week and give you feedback.

**Comment by facundo-lezama** [comment]
This got merged in https://github.com/tryolabs/norfair/pull/259. I'm closing this issue.
