### ISSUE TITLE
how can we use this tracker with yolov5 ?

### ISSUE THREAD

**Issue by akshaykadam771** [tryolabs/norfair#26]
can we use this tracker with yolov5? if yes then any documentation available for that?

**Comment by joaqo** [comment]
You can certainly run it with YOLOv5, though we don't have any demos for showing how to do that. We are under the impression that YOLOv4 is superior to YOLOv5, so I don't think we'll be adding said demo, at least for the time being.

**Comment by akshaykadam771** [comment]
ok..thanks @joaqo  for the information

**Comment by fcakyon** [comment]
@akshaykadam771 you can try the new yolov5 tracking demo! https://github.com/tryolabs/norfair/tree/master/demos/yolov5
