### ISSUE TITLE
I added yolo model trained in mmdetection I added config file and checkpoint.  by printing the result I am able to see the detection result but wrong tracked result

### ISSUE THREAD

**Issue by raju-kulkarni** [tryolabs/norfair#263]
Object_609(age: 7, hit_counter: 8, last_distance: 0.00, init_id: 609)]

result of tracked like this. I got many object like this its last_distance is 0. In every frame object, it consider as new object and provide the object id to it and not trcaked the previous detected object in last frame.

**Comment by DiegoFernandezC** [comment]
Hi @raju-kulkarni.

It appears that your issue may be related to the distance function. Could you provide some additional context to better understand this behavior? Specifically, which parameters did you use when initializing the Tracker, such as `distance_function` and `distance_threshold`?

Another potential point of failure may be the generation of Detection instances. Have you watched any demos to ensure that you are using the correct format to pass to the Tracker in the update method?

**Comment by raju-kulkarni** [comment]
It works now the problem in inference code for latest model of mmdetection it gives the result in different format. but thanks for quick reply really appreciate.
