### ISSUE TITLE
Tracking objects when detection info is empty

### ISSUE THREAD

**Issue by rose-jinyang** [tryolabs/norfair#276]
Hello
How are you?
Thanks for contributing to this project.
The object tracking result is empty when the detection info as tracker's input data is empty.
Is this an issue?
In fact, the tracking result should be NOT empty although the detection info is empty.

**Comment by aguscas** [comment]
Hello @rose-jinyang ! Sorry for the late response. I couldn't follow exactly what was the bug you were experiencing. Could you add more information on your problem? Maybe a few lines of code showing what you were trying to run could be useful.
