### ISSUE TITLE
Checking cuda availability in YOLOv4 demo

### ISSUE THREAD

**Issue by Sandman-Ren** [tryolabs/norfair#28]
Hi,

I was running your [YOLOv4 demo](https://github.com/tryolabs/norfair/blob/master/demos/yolov4/yolov4demo.py) on a standard Google Colab CPU environment earlier.  In YOLO.__init__(*) line 21, the map_location did not check the availability of CUDA. This threw me a NoneType Error which took a few minutes to locate and solve. Perhaps you can do a quick revision of this line to also include a check on cuda.is_available()?

Thanks =)

**Comment by joaqo** [comment]
Hey thanks for the bug report! Fixed it here https://github.com/tryolabs/norfair/commit/581f782c23d35c83df4c09af8cd538aac11ff376 please let me know if this catches the error on your end.
