### ISSUE TITLE
object ids in tracked_objects skipped a number?

### ISSUE THREAD

**Issue by utility-aagrawal** [tryolabs/norfair#309]
Hi,

I am using norfair to track faces. I noticed that sometimes tracked_objects were skipping a number for object ids. For example, I have 3 faces and object ids are 1, 3, 4 instead of 1,2,3. What could be the reason? Might I be doing something wrong? Let me know if you need anything additional. Thanks!

**Comment by utility-aagrawal** [comment]
This is the video you can use for testing:
https://github.com/tryolabs/norfair/assets/140737044/aedd01ff-e2e3-458f-b8ba-c7be153cc038

Please refer to issue #307 for code. The only changes I have made are:
1) skip_period = 3,
2) initialization_delay = 9
3) hit_counter_max = 15

Thanks

**Comment by utility-aagrawal** [comment]
@aguscas Could you please advise on this?

**Comment by aguscas** [comment]
Alright, I made a test using the same parameters you said for all variables, but couldn't reproduce the problem you were mentioning about skipping ids. I'm still not sure what might cause you that. Here is the [video](https://github.com/tryolabs/norfair/assets/70915567/b202425e-8ceb-44bf-88cb-e4caf17bfa44) created with your code.

By the way, these models run so slow that I shouldn't even call it 'running', it's more like crawling towards the output. Hope you find other models that run faster.

Also on another note, parameters seem to need a lot of tuning, lots of ID switches there.

**Comment by utility-aagrawal** [comment]
I should have mentioned it before. It doesn't happen for every video. I have seen it happening when you have more faces (5+) in the video. I'll try to find an example video and share with you.

**Comment by utility-aagrawal** [comment]
Here's one video you can try. You'll notice that object ids 26 and 29 are skipped:

/home/anurag/Work/FaceRedaction/test_videos/London Walk from Oxford Street to Carnaby Street_30secs.mp4

**Comment by aguscas** [comment]
Are you sure you haven't made any other changes to the code [here](https://github.com/tryolabs/norfair/issues/307#issuecomment-1969962096) apart from the values of `skip_period`, `initialization_delay` and `hit_counter_max`? I am asking because I just tried that video with your code and couldn't even get to ids that high. Are you sure you haven't at least changed any threshold, like the `distance_threshold` or any other tracking parameter?

**Comment by utility-aagrawal** [comment]
Closing this issue. I just added a postprocessing step to assign contiguous object IDs. Thanks!
