### ISSUE TITLE
Error with video variable if not run as a script

### ISSUE THREAD

**Issue by nachonacho2** [tryolabs/norfair#31]
Hi Joaqo,

Using colab, when I run the Norfair detectron2 demo code by pasting the code into a cell, I receive the following error related to this line: video = Video(input_path="./video.mp4")
ValueError: not enough values to unpack (expected 2, got 0)
(Full error pasted below)

When the same code is called as a script (!python detectron2_cars.py) it runs with no issues.
Perhaps this is not unexpected behaviour, but I can't work out why it works in a script but not in the cell.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-42-6abfe7a302d4> in <module>()
     19 
     20 # Norfair
---> 21 video = Video(input_path="./video.mp4")
     22 tracker = Tracker(distance_function=centroid_distance, distance_threshold=20)
     23 

1 frames
/usr/local/lib/python3.6/dist-packages/norfair/video.py in __init__(self, camera, input_path, output_path, output_fps, label, codec_fourcc)
     83         )
     84         self.task = self.progress_bar.add_task(
---> 85             self.abbreviate_description(description),
     86             total=total_frames,
     87             start=self.input_path is not None,

/usr/local/lib/python3.6/dist-packages/norfair/video.py in abbreviate_description(self, description)
    185     def abbreviate_description(self, description):
    186         """Conditionally abbreviate description so that progress bar fits in small terminals"""
--> 187         _, terminal_columns = os.popen("stty size", "r").read().split()
    188         space_for_description = (
    189             int(terminal_columns) - 25

ValueError: not enough values to unpack (expected 2, got 0)

**Comment by joaqo** [comment]
Hi, @nachonacho2 thanks for the issue report. Turns out that you just found a bug we introduced relatively recently! Nice find! We'll fix it ASAP and let you know when its done, thanks!

**Comment by joaqo** [comment]
Turns out the bug is fixed in the master branch of Norfair, which isn't getting picked up in your colab notebook because you are probably doing a pip install in it, and the current version in pip doesn't yet have these fixes. We are going to do a release to pip this Monday, so the bug will be fixed then!

Thanks again.

**Comment by nachonacho2** [comment]
Hi Joaqo,
Yes, you're right, I was doing a pip install. Just tested using the master branch instead and no errors.
Thanks!

**Comment by joaqo** [comment]
Hey @nachonacho2 we just released the new version (0.1.8), would you mind testing if it fixed your bug? Thanks!

**Comment by nachonacho2** [comment]
Hi @joaqo, seems to work as expected now with no errors. Thanks!

**Comment by joaqo** [comment]
Awesome, thanks for the bug report!
