### ISSUE TITLE
yolov5 integration with object detection

### ISSUE THREAD

**Issue by berkantay** [tryolabs/norfair#32]
Hello,

Thanks for the repository at first. I am working on a NVIDIA Jetson TX2 developer kit and I can detect humans with yolov5 on GPU. How to make norfair work on GPU? If we can not is it lightweight for Jetson TX2 too?

**Comment by joaqo** [comment]
Hey, thanks for the interest! Norfair actually runs on the CPU, its just numpy under the hood. We have yet to optimize it for speed, and we will soon, but it should still be fast enough to run on the Jetson TX2.

We are actually making some changes to the install process too. We are making the OpenCV dependency optional as we too run Norfair on a Jetson device and know that compiling OpenCV on that platform can be a pain, so if that gives you issues, it will be optional soon.

**Comment by berkantay** [comment]
Hello @joaqo it is nice to hear that you working on it. I will be following your updates.

**Comment by joaqo** [comment]
Thanks, but there is no need to wait though, Norfair now is fast enough to run on CPU with no issues!

**Comment by berkantay** [comment]
Which CPU do you use? Since I use Jetson TX2 I do not have much computation power on CPU side.

**Comment by joaqo** [comment]
We have tried it on a Jetson Nano with no problems. Do you have issues on the TX2?

**Comment by fcakyon** [comment]
@berkantay you can try the new yolov5 tracking demo! https://github.com/tryolabs/norfair/tree/master/demos/yolov5
