### ISSUE TITLE
face mask integration

### ISSUE THREAD

**Issue by ivibrahim** [tryolabs/norfair#34]
Hi, firstly thanks for the work. 

I'm implementing a face mask detection system over street cameras and I wonder that is there any way to integrate face mask detection with norfair tracking system. I detected faces and I use it with norfair no problem.  But when i want to integrate the face mask detection system i couldn't figure out how to track and determine whether a traced face have mask or not depending on the previous results. 

Is there any way to do that?  Thanks in advance

**Comment by joaqo** [comment]
Hi, thanks for trying Norfair! If you already have a face mask detector + Norfair working together you are almost there! You should be getting a bunch of tracked objects with unique ids on each frame of your video, and you just have to program some sort of rule with them in python to assign mask/no-mask to them.

You could do something like, "if an object with a certain id was matches with a `mask` detection for 7 of its last 10 frames then classify it as `mask`" or stuff like that. This particular rule may be too simplistic but you get the idea. We have a blogpost in which we show a face mask demo we built using Norfair if you are interested: https://tryolabs.com/blog/2020/07/09/face-mask-detection-in-street-camera-video-streams-using-ai-behind-the-curtain/

**Comment by ivibrahim** [comment]
Thanks for the answer, but i think i told wrong the issue. Yes i have a face mask detector i use it by feeding it with face detectors outputs and it gives output of whether the face is masked or not. But i could'nt make the linking between the mask detector's output and the tracking's input. How can i tell to NorFair that here is the face coordinates(face center) and here is the info of whether face is masked or not. After that how can i pick 7 masked faces out of last 10 frames?

I also examined your blogspot in detail and that was really nice and well written, congratulations!

**Comment by joaqo** [comment]
For integration with Norfair and a Detector, you can check our [demos](https://github.com/tryolabs/norfair/tree/master/demos) page, specially the Detectron2 one I suspect is similar to what you need. With regards to doing things like picking 7 masked faces out of the last 10 frames that should be quite simple to program yourself. Keep a global list of people, and on each iteration over your video update it in some way you see fit.
