### ISSUE TITLE
Any way to pass class indexes ?

### ISSUE THREAD

**Issue by dsantiago** [tryolabs/norfair#35]
Is there any way to pass class indexes to force same color for distinct classes?

**Comment by joaqo** [comment]
Hi there! Yes, Norfair only provides the tracker and support for video, so stuff like that must be coded by the user, though its very simple. In the very simple detectron cars demo we filter by cars in this line of code: 

https://github.com/tryolabs/norfair/blob/master/demos/detectron2/detectron2_cars.py#L33

You can modify the code as you see fit. Norfair doesn't have a concept of classes inside its tracker, each object has a unique id, so any detection object you pass yo it will be treated as the same class. If you want to separate detections by class you will need to create one tracker per class.
