### ISSUE TITLE
Add audio from original video

### ISSUE THREAD

**Issue by sevagh** [tryolabs/norfair#37]
Hello. I'm using Norfair to track objects in MP4 videos (which also contain audio). I'm using code similar to the OpenPose example (updated to support the new OpenPose API). Here's an excerpt of the code:

```python
import norfair
from norfair import Detection, Tracker, Video
import pyopenpose as op

frame_skip_period = 3
detection_threshold = 0.01
distance_threshold = 0.4

for input_path in args.files:
    video = Video(input_path=input_path)
    tracker = Tracker(
        distance_function=keypoints_distance,
        distance_threshold=distance_threshold,
        detection_threshold=detection_threshold,
        point_transience=2,
    )
    keypoint_dist_threshold = video.input_height / 25

    for i, frame in enumerate(video):
        detected_poses = pose_detector(frame)
        if detected_poses is not None:
            detections = (
                []
                if not detected_poses.any()
                else [
                    Detection(p, scores=s)
                    for (p, s) in zip(detected_poses[:, :, :2], detected_poses[:, :, 2])
                ]
            )
            tracked_objects = tracker.update(
                detections=detections, period=frame_skip_period
            )
            norfair.draw_points(frame, detections)
            norfair.draw_tracked_objects(frame, tracked_objects)
        video.write(frame)
```
Here's the output MP4: 
![image](https://user-images.githubusercontent.com/8574092/104611290-f608a200-5652-11eb-9241-24f4f00ffd64.png)

It has the poses overlaid appropriately. However, the original video had audio. Is there a way this can be added to the output video with Norfair?

**Comment by sevagh** [comment]
I believe this will depend on cv2's VideoCapture support for this (which doesn't look like it exists). I may need to find an external solution, then, it seems inappropriate to incorporate audio in this codebase.

**Comment by joaqo** [comment]
Hey, thanks for trying Norfair out! Regrettably I don't think OpenCV supports audio as you mentioned, and our `Video` class is based on `VideoCapture` so we don't support it either. Luckily Norfair is extremely modular, so you can just not use our `Video` class and replace it with something that supports audio. ffmpeg may be useful for this.

**Comment by sevagh** [comment]
I came up with a solution that uses MoviePy side by side with OpenCV - works fine with norfair. The trick is synchronizing real-time video and audio frames (but this is in general a hard problem in Python multimedia, not a norfair issue).

Thanks!

**Comment by joaqo** [comment]
Great, glad you got it working!
