### ISSUE TITLE
distance function examples

### ISSUE THREAD

**Issue by nikky4D** [tryolabs/norfair#46]
Are there any more examples of distance functions? I'm doing tracking with bounding boxes, and a feature extractor on the box. Is there an example that uses this type of setup for norfair?

**Comment by joaqo** [comment]
Currently we only have the examples in the demo folder of the repo, which are all spacial distances, but an example with a feature extractor (along with new tools for helping with feature extraction) are on the way!

**Comment by nikky4D** [comment]
Are there any updates on this?

**Comment by joaqo** [comment]
We'll resume working on feature extraction support early August, so I would expect this to be done by late August, early September.

**Comment by fcakyon** [comment]
@joaqo this is related to https://github.com/tryolabs/norfair/issues/36 right? Is there any progress on it?

**Comment by joaqo** [comment]
Yeah they're related, we had some delays, expect it in a couple of weeks. Thank you for your patience!

**Comment by joaqo** [comment]
Just merged https://github.com/tryolabs/norfair/pull/74 which adds support for past_predictions, its not merged yet but it should be easy to use with a local version. We'll do a release soon with it soon though.

**Comment by fcakyon** [comment]
@joaqo awesome news!
