### ISSUE TITLE
It is multi-object, but can we also do multiclass tracking simultaneously?

### ISSUE THREAD

**Issue by nmc-costa** [tryolabs/norfair#47]
Hello,

Thank you for the nice work. 
I'm still experimenting, but can we add also multiclass tracking?

**Comment by joaqo** [comment]
Hi thanks for using Norfair. Just create a separate instance of the `Tracker` class for each class of object!

**Comment by nmc-costa** [comment]
Thank you @joaqo , 

Another missing feature is drawing class id or class name. 
Or have a function that one can draw a custom text next to the tracked object.
Is it difficult to add? 

I'm going to do a patch to your draw_tracked_objects() to do just that.

Thanks,

**Comment by joaqo** [comment]
Thats a great idea, we haven't used Norfair too much for different object classes, so we never really had to deal with this, but I agree that it is something that we should add. If you create a PR I'll review it and add merge it.

Thanks!

**Comment by nmc-costa** [comment]
> Thats a great idea, we haven't used Norfair too much for different object classes, so we never really had to deal with this, but I agree that it is something that we should add. If you create a PR I'll review it!
> 
> Thanks!

Hello @joaqo 

Without being smug,  I suppose it will be easier for you to just add a function that adds a simple text to any tracker object, like the draw_debug_metrics() text.
Right now, I don't have the time to implement it. However, when I pick up norfair again, if it is not implemented, I will do the PR.

Thank you

**Comment by joaqo** [comment]
Yeah don't worry about it, this makes perfect sense. This task is now in our to do list and we'll implement it as soon as we can.

Thanks for trying out Norfair and for taking the time to suggest improvements!
