### ISSUE TITLE
can realize this project with C++？

### ISSUE THREAD

**Issue by jcyhcs** [tryolabs/norfair#48]
hi,professor:

this project is very good! but in practical use , we prefer to C++， so, can realize this project with C++? thanks!

**Comment by dekked** [comment]
Hi @jcyhcs!

Norfair is a Python library. While some parts in the future could indeed be written in C++ (for speed), it's not in the roadmap for now.

If you want to re-implement it in C++, feel free! We can link to the repository and maybe collaborate in the future :)
