### ISSUE TITLE
Wrap Darknet yolov4 in Norfair's Detection objects

### ISSUE THREAD

**Issue by wjassim** [tryolabs/norfair#49]
Hi. Thank you for the great tool. 

I am wondering if it is possible to wrap darknet-based yolov4 (https://github.com/AlexeyAB/darknet/blob/master/darknet_video.py) in Norfair's detection objects. The darknet-based yolov4 (darknet_video.py) provides detections for each detected object in the frame in the following format:

class (str), 
confidence (one value in str), and 
bbox (a tuple with 4 values). 

This is shown in the following image: 

![image](https://user-images.githubusercontent.com/67051480/118626244-9cf87880-b7c2-11eb-8c4b-b6878b38762f.png)
 
Thanks a million.

**Comment by joaqo** [comment]
Yeah it should be quite easy! Take a look at our [docs](https://github.com/tryolabs/norfair/blob/master/docs/README.md) to see in what format Detections expect their coordinates, and at our [demos](https://github.com/tryolabs/norfair/tree/master/demos) (particularly yolov4) on examples of how to do this!
