### ISSUE TITLE
Wrap YOLOv5 object detector

### ISSUE THREAD

**Issue by fcakyon** [tryolabs/norfair#50]
Are you accepting any PRs? I can create a PR for yolov5 demo using the [yolov5 pip package](https://pypi.org/project/yolov5/5.0.5/).

**Comment by joaqo** [comment]
You for sure! You can look at our other demos to get a sense of what format they follow with regards to having a short README, and how they structure their code. Thank you!

**Comment by fcakyon** [comment]
@joaqo do you have url for any of the videos you used for the demo in readme?

**Comment by fcakyon** [comment]
@joaqo created the pr at #52

**Comment by joaqo** [comment]
Thank you!
