### ISSUE TITLE
fast objects 

### ISSUE THREAD

**Issue by haviduck** [tryolabs/norfair#51]
heya, im trying to figure out what param i can tinker with to track fast moving objects. in my case the object is present in 4,5 frames. its being detected by yolo, but tracker wont pick up on it.  i set distance to a higher amount and thinking transience might be it but i dont 100% understand it.

**Comment by haviduck** [comment]
was an error with my detector. all good now!

**Comment by haviduck** [comment]
im still facing some issues with it. im trying to understand inertia but havent found an explanation that i get. i understand inertia has to do with resistance of expected movement, but the way you explain it in your docs with counting down etc just throws me iff. what practical effect does those two params have for my objects?

  my scenario is that a bunch of objects gets thrown down a slide at various speeds. the faster ones gets picked up by my detector, but norfair wont put them in matched.

**Comment by joaqo** [comment]
Yeah sure, how it works is quite simple. What we consider to be an object or not depends on how many hits that object gets. We consider a hit to be a match between an object and a detection.

The lifecycle of an object is as follows:

- When a detection doesn't get matched to any object, it is transformed into a potential object. It starts with a hit counter of 1, as it has just been created, and has only gotten a single hit.
- As the new potential object starts getting new hits, its hit counter starts increasing. When its hit counter goes over `hit_inertia_min  + initialization_delay` the object is now considered a real object, and is returned to the user for the first time.
- After the object is considered real, it will start getting more matches and misses, and its hit counter will go up and down. If it goes below `hit_inertia_min` the object is considered dead and Norfair deletes it. If it goes above `hit_inertia_max` its hit counter won't increase anymore, as it could increase infinitely and it would have too much 'inertia" and would then take too long to die after it stops getting matches. So an object's hit counter will always stay between `hit_inertia_min` and `hit_inertia_max` as long as the object is alive.

In your case you would need to set `initialization_delay` and `hit_inertia_min` to a very low number so you ensure your objects start being considered real as soon as it appears. Be careful, if you set these number too low Norfair wont filter out incorrect detections.

Good luck!

**Comment by haviduck** [comment]
thanks a bunch for explaining that thoroughly, man. appreciate it.

**Comment by joaqo** [comment]
No problem, we should probably be adding this to the documentation now that I think about it 😂. @dekked this could be an easy first PR for someone coming into Norfair.
