### ISSUE TITLE
Import metrics error 

### ISSUE THREAD

**Issue by abhigoku10** [tryolabs/norfair#60]
@gerhc @draix @dekked  hi thanks for sharing this source code when i try to install pip install norfair[video]  # Adds several video helper features running on OpenCV
pip install norfair[metrics]  # Supports running MOT metrics evaluation
pip install norfair[metrics,video]  # Everything included
 I i get the following error "ImportError: cannot import name 'metrics'"

Please let me knw what is the issue

**Comment by dekked** [comment]
Hi @abhigoku10

Can you show us what is the exact script you run to get the `ImportError`?

Does it happen if you `pip uninstall norfair` and then only run `pip install norfair[metrics,video]`?

**Comment by dekked** [comment]
Can you paste the output of **a fresh** `pip install norfair[metrics,video]`?

**Comment by abhigoku10** [comment]
@dekked  i checked in multiple systems both on windows and linux yet i am getting the same error

**Comment by dekked** [comment]
Hi @abhigoku10, I am really trying to help you here, but if you don't paste what I asked for in my previous comment, there is not much else I can do.

**Comment by abhigoku10** [comment]
@dekked  apologies for the difference in understanding please find the output of the installation 
Requirement already satisfied: norfair[metrics,video] in c:\python36\lib\site-packages (0.1.8)
WARNING: norfair 0.1.8 does not provide the extra 'metrics'
WARNING: norfair 0.1.8 does not provide the extra 'video'
Requirement already satisfied: filterpy<2.0.0,>=1.4.5 in c:\python36\lib\site-packages (from norfair[metrics,video]) (1.4.5)
Requirement already satisfied: rich<7.0.0,>=6.1.1 in c:\python36\lib\site-packages (from norfair[metrics,video]) (6.2.0)
Requirement already satisfied: opencv-python<5.0.0,>=3.2.0 in c:\users\ska10\appdata\roaming\python\python36\site-packages (from norfair[metrics,video]) (4.5.1.48)
Requirement already satisfied: scipy in c:\users\ska10\appdata\roaming\python\python36\site-packages (from filterpy<2.0.0,>=1.4.5->norfair[metrics,video]) (1.5.4)
Requirement already satisfied: numpy in c:\python36\lib\site-packages (from filterpy<2.0.0,>=1.4.5->norfair[metrics,video]) (1.19.5)
Requirement already satisfied: matplotlib in c:\python36\lib\site-packages (from filterpy<2.0.0,>=1.4.5->norfair[metrics,video]) (3.3.4)
Requirement already satisfied: typing-extensions<4.0.0,>=3.7.4 in c:\python36\lib\site-packages (from rich<7.0.0,>=6.1.1->norfair[metrics,video]) (3.7.4.3)
Requirement already satisfied: dataclasses<0.8,>=0.7 in c:\python36\lib\site-packages (from rich<7.0.0,>=6.1.1->norfair[metrics,video]) (0.7)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\users\ska10\appdata\roaming\python\python36\site-packages (from rich<7.0.0,>=6.1.1->norfair[metrics,video]) (2.8.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in c:\users\ska10\appdata\roaming\python\python36\site-packages (from rich<7.0.0,>=6.1.1->norfair[metrics,video]) (0.4.4)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\python36\lib\site-packages (from rich<7.0.0,>=6.1.1->norfair[metrics,video]) (0.9.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\ska10\appdata\roaming\python\python36\site-packages (from matplotlib->filterpy<2.0.0,>=1.4.5->norfair[metrics,video]) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\ska10\appdata\roaming\python\python36\site-packages (from matplotlib->filterpy<2.0.0,>=1.4.5->norfair[metrics,video]) (2.8.1)
Requirement already satisfied: cycler>=0.10 in c:\python36\lib\site-packages (from matplotlib->filterpy<2.0.0,>=1.4.5->norfair[metrics,video]) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\python36\lib\site-packages (from matplotlib->filterpy<2.0.0,>=1.4.5->norfair[metrics,video]) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in c:\python36\lib\site-packages (from matplotlib->filterpy<2.0.0,>=1.4.5->norfair[metrics,video]) (8.1.2)
Requirement already satisfied: six in c:\python36\lib\site-packages (from cycler>=0.10->matplotlib->filterpy<2.0.0,>=1.4.5->norfair[metrics,video]) (1.15.0)

what i was able to find out is norfair==0.1.8 version is getting installed and the latest is 0.3.0 version

**Comment by dekked** [comment]
What happens is the latest version of Norfair doesn't support Python 3.6, only 3.7+.

Therefore, you are installing a previous version which does not have the "metrics" module.

You need to upgrade your Python installation or use a tool like Pyenv.
