### ISSUE TITLE
Tracking for my own ojects.

### ISSUE THREAD

**Issue by domilay** [tryolabs/norfair#62]
Hello, thanks for the great work. My question is: I have trained weights for my custom objects. Could I just applied the weights and track the custom objects? Thanks a lot.

Meanwhile, in testing, I found there is a problem about drawbox: 

module 'norfair' has no attribute 'draw_boxes'

**Comment by joaqo** [comment]
Hey @domilay , yeah, you can use any neural network with any weights you want. Norfair itself has no weights as its not a neural network. Regarding your error, is it possible you are using an old version of Norfair? Can you post your version here?

**Comment by haviduck** [comment]
you mean draw_points?
