### ISSUE TITLE
Speeding up detection and tracking processes

### ISSUE THREAD

**Issue by wjassim** [tryolabs/norfair#66]
Hi,

Thank you for the useful tracker. I just wanted to ask if it is possible to run a  detector (such as yolo) to detect objects every N frames only, while norfair tracks objects and fills in the gaps efficiently to speed up the overall process. Running yolo or any other detector for each frame all the time might slow down the FPS.

If the idea is workable, which function from norfair can do the tracking when the detector is disabled? 

Thanks a million..

**Comment by haviduck** [comment]
thats gonna be pretty inaccurate but something like this:


```
vs = cv2.VideoCapture(0)
frameno=1
while True:
    grabbed, frame = vs.read()
    if frameno%5==0 and grabbed:
        #do your detect every 5th frame 
        #update tracker and draw
        cv2.waitKey(1)
    frameno+=1

```

**Comment by wjassim** [comment]
> thats gonna be pretty inaccurate and you gonna have to up the max distance and probably write a better euclidean but something like this:
> 
> 
> 
> 
> 
> ```
> 
> vs = cv2.VideoCapture(0)
> 
> frameno=1
> 
> while True:
> 
>     grabbed, frame = vs.read()
> 
>     if frameno%5==0 and grabbed:
> 
>         #do your detect every 5th frame 
> 
>         #update tracker and draw
> 
>         cv2.waitKey(1)
> 
>     frameno+=1
> 
> 
> 
> ```

Thank you for your feedback.This looks promising but I was wondering if norfair can predict positions for the 6th frame base on previous position from the 5th, 4th, 3rd and other frames. Is there any function from the tracker to do that?

**Comment by haviduck** [comment]
ahh, i getcha, sorrt. no, not from what ive seen.

**Comment by dekked** [comment]
Hi @wjassim

Is what you describe equivalent to what we do in the [OpenPose demo](https://github.com/tryolabs/norfair/tree/master/demos/openpose)?

**Comment by wjassim** [comment]
Hi @dekked, 

Wonderful! that's what I was looking for. Thank you for the great note. Best regards..

**Comment by dekked** [comment]
Great! Glad to be of help. I am closing the issue, feel free to create an Issue for any further question.
