### ISSUE TITLE
norfair with yolov5

### ISSUE THREAD

**Issue by Hilal-Urun** [tryolabs/norfair#68]
hi, I just tried to real time- detect people and want to get  for example named A person enter and camera saw it then first x,y coordinate and last one according to tracking but I couldnt. I also can not show the ids on the frame.. I examined on README tutorial but I can not still fix it. Could you help me ?

**Comment by joaqo** [comment]
Hi @Hilal-Urun Norfair is meant to give you tracking, all other custom logic you may want to add on top of that will need to be handled on your end.

So for example if you want to save where you first saw a person and when you last saw it, you'll need to keep a dict external to Norfair, and as you iterate over the video feed frames, and receive tracks from Norfair on each frame, update this dict: if an id is not on the dict, you know that it is a person you've seen for the first time, and therefore should save its current x, y coordinates as its initial coordinates. Also update its last seen coordinate.

Regarding drawing the ids on the frame, Norfair provides a drawing function which draws the id of each object on each frame. Find its doc [here](https://github.com/tryolabs/norfair/tree/master/docs#draw_debug_metrics). It's also used in our demos, so i'd check those too.

**Comment by Hilal-Urun** [comment]
I got it, thanks a lot @joaqo
