### ISSUE TITLE
Tracking objects in multiple cameras 

### ISSUE THREAD

**Issue by YoussefSaad1** [tryolabs/norfair#69]
Hello, What if I have multiple cameras, for example, 2 cameras and need to track the object from these 2 cameras, is this applicable?

**Comment by joaqo** [comment]
We haven't really faced this use case before, but I guess you could create a distance function which uses the camera_id metadata to make sure the associations between objects of different cameras is being done correctly. It actually sounds quite interesting, please keep us posted.
