### ISSUE TITLE
Citation information

### ISSUE THREAD

**Issue by bjarnekvae** [tryolabs/norfair#70]
This tool is amazing, and deserves to be cited in my work. Can you please provide the name of the authors so I can cite this tool properly?

**Comment by dekked** [comment]
Hi @bjarnekvae!

We are honored to be cited in your work (if it's open, a link, when it's finished would be awesome!).

We have added instructions for citing [to the main README](https://github.com/tryolabs/norfair#citing-norfair).

Hope this is enough for your case :)
