### ISSUE TITLE
Tracking static objects with moving camera

### ISSUE THREAD

**Issue by ddd-20** [tryolabs/norfair#71]
Hi,

I am trying to track static objects on the road with a camera mounted to a moving vehicle. I set `hit_inertia_min` to 1, `hit_inertia_max` to 10 and `point_transcience` to 50. I noticed that at certain vehicle speeds, the tracking works fine. However, at slower speeds in a parking lot for example, the same object in view is interpreted as new object every few seconds. Is this because of `hit_inertia_max`? 
What parameters are recommended to change and can we change these dynamically based on vehicle speed while tracking is in progress?

**Comment by joaqo** [comment]
Hi, @ddd-20, it could be several things, the inertias may be too low, your tracker may be getting spotty detections from the detector, you could have occlusion problems, etc. Its hard to know without looking at the video. You may try using [draw_debug_metrics](https://github.com/tryolabs/norfair/tree/master/docs#draw_debug_metrics), to help you find out whats happening in though!
