### ISSUE TITLE
How to kill tracks when they leave scene?

### ISSUE THREAD

**Issue by ManuConcepBrito** [tryolabs/norfair#75]
First of all, thanks for the package. I am currently working on tracking cars using the detections from a yolov5 network. The problem is that it works fine when cars go through different lanes. My problem is that I am recording an entrance and exit (same lane) and when a car leaves and another one enters they get matched as the same car. I tried reducing the point_transience but that did not really help. Also, is there a common practice when setting up the hyperparameters of the tracker (like recording the average distance between detections?

**Comment by joaqo** [comment]
@ManuConcepBrito That is odd, if the object leaves the scene for some time the object_id should be removed from the pool, and a new object_id should be assigned for the object that enters the scene. You may have your `hit_inertia_max` be too high.

@nikky4D Just set `past_detections_length` to how many detections you want to keep through the life of the project, and then if you want embeddings just add embeddings to the `.data` property of the object, which you can later use in you distance function. This is not properly documented at the moment, and there are no examples, but we'll add some soon. [Docs](https://github.com/tryolabs/norfair/tree/master/docs)

**Comment by ManuConcepBrito** [comment]
Thanks for the help! I finally figured out the issue. We were only passing detections to the tracker when a detection was in the frame so we skipped the empty frames and that's why it didn't kill the tracked objects.

**Comment by joaqo** [comment]
Awesome!
