### ISSUE TITLE
Get the index of input detections based on object id

### ISSUE THREAD

**Issue by chenzhutian** [tryolabs/norfair#77]
Hi thanks for the great work.
I want to get the index of input detections based on an object id, how can I achieve that ?
For example, I tried:
```python
detections = [Detection(p) for p in predictions.pred_boxes.get_centers().numpy()]
tracked_objects = tracker.update(detections=detections)

## I want to get the detections of objects whose id are 1 or 2
targeted_ids = [1, 2]
targeted_idx = [idx for idx, tObj in enumerate(tracked_objects) if tObj.id in targeted_ids]

## however, this is not I want to track
targeted_detections = detections[targeted_idx]
```
However, it turns out that the targeted_detections are not the objects I am interested in (i.e., with tracked id 1 or 2)

Thanks!

**Comment by joaqo** [comment]
Hey! Each object is associated with many detections to its lifetime, so there isn't a 1 to 1 relationship there. What you can do is access the `.last_detection` attribute of the tracked object. Its detailed better in the docs.

**Comment by chenzhutian** [comment]
Great! I pass the index to the `detection.data` and fix it.
Thanks a lot!
