### ISSUE TITLE
Detection and TrackedObject classes should contain class label (when applicable)

### ISSUE THREAD

**Issue by Uzarel** [tryolabs/norfair#84]
Hi,
before I begin I would like to thank you for the amazing work on this library and for the clear repo!

As the title suggests, I can't see why you are not giving end-users the possibility to keep track of class labels when working with traditional object detector. I read that you added the data attribute to the Detection class (which can store them eventually), and I also read on issue #47 that you don't use Norfair too much for different object classes, but I still think that an (optional) attribute regarding object classes would be great.

I was working on tracking different object classes, and I think it would be not optimal of me instantiating multiple trackers in order to keep track of multiple object classes. I guess the codebase right now is not ready to handle multiple classes in a single tracker, since different classes could be mixed up together by mistake, even though it would be a really nice addition.

If I had a class-label attribute for the Detection and/or TrackedObjects classes, I would love that.

Thanks for the hard work!

**Comment by joaqo** [comment]
Hi @Uzarel, thanks for the feedback! We gave this idea another visit, and we're probably going to be adding it to the library. We're still in the process of making the final decision though, and more specifically trying to sketch out how this would look in code.
