### ISSUE TITLE
Detection class label

### ISSUE THREAD

**Issue by Auth0rM0rgan** [tryolabs/norfair#92]
Hi @joaqo, thank you for the amazing work! 

Im currently using deepsort with yolov5 for tracking the objects that Im interested in. I would like to change the deep sort and use your library which is faster. However I a question regard to results of the tracking. In Deepsort, Im able to return Tracker_id, Class name, confidence score and bbox. I wanted to ask you is there any way to access to these information via norfair tracking? I tried to access these information but no success. Would appropriate any help..

Thanks!

**Comment by joaqo** [comment]
Hey! I guess you already guessed it from the linked PR, but this latest PR adds this feature. It's not yet released, so you'll have to clone the repo to make use of it!
