### ISSUE TITLE
Question: How to implement vehicle speed tracking?

### ISSUE THREAD

**Issue by raivil** [tryolabs/norfair#94]
Hi,
Would it be possible to implement a simple vehicle speed tracking based on https://github.com/tryolabs/norfair/blob/master/demos/yolov5/yolov5demo.py code?

I'm new to the area and I'm trying to understand what would be the steps to implement it?

Thank you.

**Comment by joaqo** [comment]
Hey! Yeah it would be possible, you'd need a way to understand how distances in pixel-space on the image translates to distances in the real world, so you'd need to create a mapping for that. This is more of a classical CV task than an ML task though.
